name: Code Lint

on: push

jobs:
  run-tests:
    name: Checking the code
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installing Hatch
        run: pip install --upgrade hatch

      - name: Running project Lint
        run: hatch run lint
