name: Code Lint

on: push

jobs:
  run-tests:
    name: Checking the code
    runs-on: ubuntu-latest
    steps:
      - name: Code Lint
        uses: Matter-Tech/matter-actions/.github/workflows/lint.yml
