name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to base the release from'
        required: true
        default: ''
      release-type:
        description: 'Release type? (major/minor/fix)'
        required: true
        default: ''


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      ref: ${{ github.event.inputs.branch }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: pyproject.toml

    - name: Installing Hatch
      run: pip install --upgrade hatch

    - name: Getting current version
      id: current-version
      run:
        echo "version=`hatch version`" >> $GITHUB_OUTPUT

    - name: Bumping version
      if: github.event.inputs.release-type == 'major' || github.event.inputs.release-type == 'minor' || github.event.inputs.release-type == 'fix'
      id: bumped-version
      run: | 
        hatch version ${{github.event.inputs.release-type}}
        echo "version=`hatch version`" >> $GITHUB_OUTPUT

    - name: Creating PR with new version
      run: gh pr create --title "Preparing release to ${{ steps.bumped-version.outputs.version }}"
